# Generated by Django 5.2.4 on 2025-09-07 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pupss', '0002_alter_document_options_document_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'permissions': [('upload_create', 'Can upload files (auto-converts)'), ('upload_read', 'Can view uploaded files & results'), ('upload_delete', 'Can delete uploaded files & results'), ('convert_rerun', 'Can manually re-run conversions'), ('system_manage', 'Can manage system settings'), ('user_manage', 'Can manage users & roles'), ('audit_read', 'Can view logs and history')]},
        ),
    ]
